version: '3.7'
networks:
  obref:
services:

  mongo-mongodb:
    container_name: mongo-mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/:/docker-entrypoint-initdb.d/:ro
      - $PWD/mongodata:/data/db  # Persist mongo data to $HOME/mongo
    hostname: mongo-mongodb
    networks:
      obref:

  config:
    container_name: config
    image: eu.gcr.io/openbanking-214714/obri/config
    ports:
      - "8888:8888"
    environment:
      CONFIG_GIT_IGNORE_LOCAL_SSH: "false"
      SPRING_PROFILES_ACTIVE: native,console-logging
      java_opts: -Xmx256m -XX:+UseConcMarkSweepGC -Dserver.port=8888
      HOSTNAME: config
    networks:
      obref:
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "http://localhost:8888/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  admin:
    container_name: admin
    image: eu.gcr.io/openbanking-214714/obri/admin
    ports:
      - "8082:8082"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config.dev-ob.forgerock.financial:8888
      SPRING_PROFILES_ACTIVE: native,console-logging
      java_opts: -Xmx256m -XX:+UseConcMarkSweepGC -Dserver.port=8082
      HOSTNAME: admin
    volumes:
      - ./forgerock-openbanking-backstage/forgerock-openbanking-admin/src/main/resources/unfiltered/keystore/keystore.jks:/opt/ob/config/keystore.jks:ro
      - ./forgerock-openbanking-backstage/forgerock-openbanking-admin/src/main/resources/unfiltered/keystore/truststore.jks:/etc/ssl/certs/java/cacerts
    networks:
      obref:
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8082/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  jwkms:
    container_name: jwkms
    image: eu.gcr.io/openbanking-214714/obri/jwkms
    ports:
      - "8097:8097"
      - "9097:9097"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config.dev-ob.forgerock.financial:8888
      SPRING_PROFILES_ACTIVE: native,console-logging
      java_opts: -Xmx256m -XX:+UseConcMarkSweepGC -Dserver.port=8097 -Dam.internal-port=8443 -Dam.port=8074
      HOSTNAME: jwkms
      CONSOLE_LOG_PATTERN: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%X{traceId}]){green} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:9097,server=y,suspend=n
    volumes:
      - ./forgerock-openbanking-jwkms/src/main/resources/unfiltered/keystore/keystore.jks:/opt/ob/config/keystore.jks:ro
      - ./forgerock-openbanking-jwkms/src/main/resources/unfiltered/keystore/truststore.jks:/etc/ssl/certs/java/cacerts
    networks:
      obref:
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8097/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  directory-services:
    container_name: directory-services
    image: eu.gcr.io/openbanking-214714/obri/directory-services
    ports:
      - "8076:8076"
      - "9076:9076"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config.dev-ob.forgerock.financial:8888
      SPRING_PROFILES_ACTIVE: native,console-logging
      java_opts: -Xmx256m -XX:+UseConcMarkSweepGC -Dserver.port=8076 -Dam.internal-port=8443 -Dam.port=8074
      HOSTNAME: directory-services
      CONSOLE_LOG_PATTERN: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%X{traceId}]){green} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:9076,server=y,suspend=n
    volumes:
      - ./forgerock-openbanking-directory-services/src/main/resources/unfiltered/keystore/keystore.jks:/opt/ob/config/keystore.jks:ro
      - ./forgerock-openbanking-directory-services/src/main/resources/unfiltered/keystore/truststore.jks:/etc/ssl/certs/java/cacerts
    networks:
      obref:
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8076/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  scgw:
    container_name: scgw
    image: eu.gcr.io/openbanking-214714/obri/scgw
    ports:
      - "8074:8074"
      - "9074:9074"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config.dev-ob.forgerock.financial:8888
      SPRING_PROFILES_ACTIVE: native,console-logging
      java_opts: -Xmx256m -XX:+UseConcMarkSweepGC -Dserver.port=8074 -Dam.internal-port=8443 -Dam.port=8074
      HOSTNAME: scgw
      CONSOLE_LOG_PATTERN: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%X{traceId}]){green} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:9074,server=y,suspend=n
    volumes:
      - ./forgerock-openbanking-gateway/src/main/resources/unfiltered/keystore/keystore.jks:/opt/ob/config/keystore.jks:ro
      - ./forgerock-openbanking-gateway/src/main/resources/unfiltered/keystore/truststore.jks:/etc/ssl/certs/java/cacerts
    networks:
      obref:
        aliases:
          - service.metrics.dev-ob.forgerock.financial
          - service.directory.dev-ob.forgerock.financial
          - am.dev-ob.forgerock.financial
          - as.aspsp.dev-ob.forgerock.financial
          - matls.service.directory.dev-ob.forgerock.financial
          - matls.rs.aspsp.dev-ob.forgerock.financial
          - matls.service.bank.dev-ob.forgerock.financial
          - service.bank.dev-ob.forgerock.financial
          - jwkms.dev-ob.forgerock.financial
          - matls.as.aspsp.dev-ob.forgerock.financial
          - swagger.dev-ob.forgerock.financial
          - scgw.dev-ob.forgerock.financial
          - rcs.aspsp.dev-ob.forgerock.financial
          - admin.dev-ob.forgerock.financial
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8074/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  as-api:
    container_name: as-api
    image: eu.gcr.io/openbanking-214714/obri/as-api
    ports:
      - "8066:8066"
      - "9066:9066"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config.dev-ob.forgerock.financial:8888
      SPRING_PROFILES_ACTIVE: native,console-logging
      java_opts: -Xmx256m -XX:+UseConcMarkSweepGC -Dserver.port=8066 -Dam.internal-port=8443 -Dam.port=8074
      HOSTNAME: as-api
      CONSOLE_LOG_PATTERN: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%X{traceId}]){green} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:9066,server=y,suspend=n
    volumes:
      - ./forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/src/main/resources/unfiltered/keystore/keystore.jks:/opt/ob/config/keystore.jks:ro
      - ./forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/src/main/resources/unfiltered/keystore/truststore.jks:/etc/ssl/certs/java/cacerts
    networks:
      obref:
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8066/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  rs-api:
    container_name: rs-api
    image: eu.gcr.io/openbanking-214714/obri/rs-api
    ports:
      - "8094:8094"
      - "9094:9094"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config.dev-ob.forgerock.financial:8888
      SPRING_PROFILES_ACTIVE: native,console-logging
      java_opts: -Xmx256m -XX:+UseConcMarkSweepGC -Dserver.port=8094 -Dam.internal-port=8443 -Dam.port=8074
      HOSTNAME: rs-api
      CONSOLE_LOG_PATTERN: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%X{traceId}]){green} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:9094,server=y,suspend=n
    volumes:
      - ./forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/resources/unfiltered/keystore/keystore.jks:/opt/ob/config/keystore.jks:ro
      - ./forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/resources/unfiltered/keystore/truststore.jks:/etc/ssl/certs/java/cacerts
    networks:
      obref:
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8094/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  rs-rcs:
    container_name: rs-rcs
    image: eu.gcr.io/openbanking-214714/obri/rs-rcs
    ports:
      - "8084:8084"
      - "9084:9084"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config.dev-ob.forgerock.financial:8888
      SPRING_PROFILES_ACTIVE: native,console-logging
      java_opts: -Xmx256m -XX:+UseConcMarkSweepGC -Dserver.port=8084 -Dam.internal-port=8443 -Dam.port=8074
      HOSTNAME: rs-rcs
      CONSOLE_LOG_PATTERN: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%X{traceId}]){green} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:9084,server=y,suspend=n
    volumes:
      - ./forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/src/main/resources/unfiltered/keystore/keystore.jks:/opt/ob/config/keystore.jks:ro
      - ./forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/src/main/resources/unfiltered/keystore/truststore.jks:/etc/ssl/certs/java/cacerts
    networks:
      obref:
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8084/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  rs-store:
    container_name: rs-store
    image: eu.gcr.io/openbanking-214714/obri/rs-store
    ports:
      - "8086:8086"
      - "9086:9086"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config.dev-ob.forgerock.financial:8888
      SPRING_PROFILES_ACTIVE: native,console-logging
      java_opts: -Xmx256m -XX:+UseConcMarkSweepGC -Dserver.port=8086
      HOSTNAME: rs-store
      CONSOLE_LOG_PATTERN: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%X{traceId}]){green} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:9086,server=y,suspend=n
    volumes:
      - ./forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/resources/unfiltered/keystore/keystore.jks:/opt/ob/config/keystore.jks:ro
      - ./forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/resources/unfiltered/keystore/truststore.jks:/etc/ssl/certs/java/cacerts
    networks:
      obref:
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8086/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  rs-ui:
    container_name: rs-ui
    image: eu.gcr.io/openbanking-214714/obri/rs-ui
    ports:
      - "8092:8092"
      - "9092:9092"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config.dev-ob.forgerock.financial:8888
      SPRING_PROFILES_ACTIVE: native,console-logging
      java_opts: -Xmx256m -XX:+UseConcMarkSweepGC -Dserver.port=8092 -Dam.internal-port=8443
      HOSTNAME: rs-ui
      CONSOLE_LOG_PATTERN: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%X{traceId}]){green} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:9092,server=y,suspend=n
    volumes:
      - ./forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/resources/unfiltered/keystore/keystore.jks:/opt/ob/config/keystore.jks:ro
      - ./forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/resources/unfiltered/keystore/truststore.jks:/etc/ssl/certs/java/cacerts
    networks:
      obref:
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8092/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  monitoring:
    container_name: monitoring
    image: eu.gcr.io/openbanking-214714/obri/monitoring
    ports:
      - "8073:8073"
      - "9073:9073"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config.dev-ob.forgerock.financial:8888
      SPRING_PROFILES_ACTIVE: native,console-logging
      java_opts: -Xmx256m -XX:+UseConcMarkSweepGC -Dserver.port=8073 -Dam.internal-port=8443
      HOSTNAME: monitoring
      CONSOLE_LOG_PATTERN: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%X{traceId}]){green} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:9073,server=y,suspend=n
    volumes:
      - ./forgerock-openbanking-backstage/forgerock-openbanking-monitoring/src/main/resources/unfiltered/keystore/keystore.jks:/opt/ob/config/keystore.jks:ro
      - ./forgerock-openbanking-backstage/forgerock-openbanking-monitoring/src/main/resources/unfiltered/keystore/truststore.jks:/etc/ssl/certs/java/cacerts
    networks:
      obref:
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8073/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  metrics-service:
    container_name: metrics-services
    image: eu.gcr.io/openbanking-214714/obri/metrics-service
    ports:
      - "8098:8098"
      - "9098:9098"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config.dev-ob.forgerock.financial:8888
      SPRING_PROFILES_ACTIVE: native,console-logging
      java_opts: -Xmx256m -XX:+UseConcMarkSweepGC -Dserver.port=8098 -Dam.internal-port=8443
      HOSTNAME: metrics-services
      CONSOLE_LOG_PATTERN: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%X{traceId}]){green} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:9098,server=y,suspend=n
    volumes:
      - ./forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/src/main/resources/unfiltered/keystore/keystore.jks:/opt/ob/config/keystore.jks:ro
      - ./forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/src/main/resources/unfiltered/keystore/truststore.jks:/etc/ssl/certs/java/cacerts
    networks:
      obref:
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8098/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  openam:
    build:
      context: .
      dockerfile: forgerock-am/Dockerfile
      args:
        # @see README file to get the binaries
        AM_WAR_NAME: "OpenAM-6.5.1.war"
        AM_PATCH_ZIP: "openbanking-1-2-tpatch.zip"
        AMSTER_ZIP: "Amster-6.5.1.zip"
    image: openam:local
    container_name: openam
    ports:
      - "80:8080"
      - "443:8443"
      - "5005:5005" # debug port, @see https://github.com/ForgeCloud/ob-deploy/wiki/Debugging-Open-Banking-AM#debug-configuration-for-intellij
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
    networks:
      obref:

  auth-ui:
    image: eu.gcr.io/openbanking-214714/obri/auth-ui
    container_name: auth-ui
    ports:
      - "4203:443"
    environment:
      DOMAIN: .dev-ob.forgerock.financial
      AUTHENTICATION_URL: https://am.dev-ob.forgerock.financial:8074
      DIRECTORY_BACKEND_URL: https://service.directory.dev-ob.forgerock.financial:8074/directory-services
    volumes:
      - ./keystore/ui/dev-ob.forgerock.financial.key:/etc/nginx/certs/dev-ob.forgerock.financial.key
      - ./keystore/ui/dev-ob.forgerock.financial.crt:/etc/nginx/certs/dev-ob.forgerock.financial.crt
      - ./keystore/ui/dev-ob.forgerock.financial.conf:/etc/nginx/conf.d/default.conf

  directory-ui:
    image: eu.gcr.io/openbanking-214714/obri/directory-ui
    container_name: directory-ui
    ports:
      - "4202:443"
    environment:
      DOMAIN: .dev-ob.forgerock.financial
      DIRECTORY_BACKEND_URL: https://service.directory.dev-ob.forgerock.financial:8074
      AUTHENTICATION_URL: https://am.dev-ob.forgerock.financial:8074
      ACCOUNT_REQUEST_BACKEND_URL: https://rs.aspsp.dev-ob.forgerock.financial:8074/api/account-requests
    volumes:
      - ./keystore/ui/dev-ob.forgerock.financial.key:/etc/nginx/certs/dev-ob.forgerock.financial.key
      - ./keystore/ui/dev-ob.forgerock.financial.crt:/etc/nginx/certs/dev-ob.forgerock.financial.crt
      - ./keystore/ui/dev-ob.forgerock.financial.conf:/etc/nginx/conf.d/default.conf

  bank-ui:
    image: eu.gcr.io/openbanking-214714/obri/bank-ui
    container_name: bank-ui
    ports:
      - "4201:443"
    environment:
      DOMAIN: .dev-ob.forgerock.financial
      AUTHORIZATION_URL: https://as.aspsp.ui-dev.forgerock.financial
      AUTHENTICATION_URL: https://am.dev-ob.forgerock.financial:8074
      REMOVE_CONSENT_URL: https://rcs.aspsp.dev-ob.forgerock.financial:8074
    volumes:
      - ./keystore/ui/dev-ob.forgerock.financial.key:/etc/nginx/certs/dev-ob.forgerock.financial.key
      - ./keystore/ui/dev-ob.forgerock.financial.crt:/etc/nginx/certs/dev-ob.forgerock.financial.crt
      - ./keystore/ui/dev-ob.forgerock.financial.conf:/etc/nginx/conf.d/default.conf