scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'config-service'
    scheme: https
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    tls_config:
          insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:8888']
  - job_name: 'discovery-service'
    scheme: https
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    tls_config:
          insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:8087']
  - job_name: 'jwkms'
    scheme: https
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    tls_config:
          insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:8097']