version: '2'
services:
 config-rs-rcs:
  container_name: config-scgw
  # image: eu.gcr.io/openbanking-214714/obri/config$TAG
  image: $IMAGE
  ports:
   - "18887:8888"
  environment:
   - spring_profiles_active=native,console-logging
  networks:
   default:
    aliases:
    - config.dev-ob.forgerock.financial