
== Quickstart
This quickstart guide aims to get you exploring OBRI quickly.

=== Getting Started
==== Becoming a TPP

. Go to link:++https://directory.{{obriDomain}}++[https://directory.{{obriDomain}}]
. Click `Sign Up`
. Enter your details and agree to the terms and conditions
. Click `Sign Up`
. Log in with you username and password

Refer to <<#_forgerock_directory_registration,ForgeRock Directory registration>> for more information.

==== Registering a Software Statement (Fintech App)
. Go to the Software Statement tab
. Click `Create a new software statement`
. In the general tab update
  * Name: Postman
  * Redirect URIs: https://www.google.com
. Click `Save`

NOTE: There is a bug with the Redirect URI text field that causes it to lose focus after every key press. Just copy and paste `https://www.google.com` in.

==== Downloading Transport Client Certificates
. Go to the Software Statement tab
. Click `See More` on your Software Statement
. Go to the `Transport/Signing/Encryption keys` tab
. Scroll to the Key's group at the bottom of the page
. Click the Action button of the key with the type equal to 'Transport'
. Download the .pem file
. Download the .key file

==== Setting up postman
Install the Postman Native App https://www.getpostman.com/apps

===== Automatic setup
. Open Postman
. Go to https://postman.ob.forgerock.financial
On Mac (& Windows?) you can:
. Click `Run in PostMan`
. Click `Postman for Mac`
. Click Open Postman
. Click the Environment dropdown. The default value in the dropdown will be `No Environment`
. Select `ForgeRock OBRI prod`

===== Manual setup
. Open Postman
. Click import
. Select the 'Import from a Link' tab
. Enter the following URL to import the Environment:
  https://raw.githubusercontent.com/ForgeRock/obri-postman/master/Environment/OpenBanking%20Engineering%20ob.postman_environment.json
. Click import
. Select the 'Import from a Link' tab
. Enter the following URL to import the Collection:
  https://github.com/ForgeRock/obri-postman/raw/master/Collection/ForgeRock_OBRI_Sample_-_V3.0.json
. Click the Environment dropdown. The default value in the dropdown will be `No Environment`
. Select `ForgeRock OBRI prod`

Refer to <<#_setting_up_postman,Setting up Postman>> for more information.

==== Add Certificate to Postman

. In Postman go to Preferences or Settings (dependent on system) -> Certificates
. Click on 'Add Certificate'
. Add the domain `*.{{obriDomain}}`
. Choose your CRT file, which can be a .pem file
. Choose your Key file, which is your .key file
. Click 'Add'

Refer to <<#_setup_your_client_certificate,Setup your client certificate>> for more information.

Check you certificates

. In Postman Collections, go to `Setup your environment` -> `Test MATLS` directory
. Select `JWKMS test MATLS`
. Click `Send` and expect a `200 OK` response
. There should also a message in the response saying `Hello {your_id}` and and a single authority called "ROLE_JWKMS_APP"
. Repeat for each test MATLS call in this directory. There should all return 200 and have an ID and some roles or authorities in the response.

==== Set Up Postman Variables
Initialise Postman variables by calling the discovery endpoints

. In Postman Collections, go to `Setup environment` -> `Discovery` directory
. Select `RS discovery`
. Click `Send` and expect a `200 OK` response
. Select `AS discovery`
. Click `Send` and expect a `200 OK` response

Refer to <<#_aspsp_discovery,ASPSP discovery>> for more information.

=== Onboarding

For all of the examples in this section the Postman functions live in `Dynamic Registration` -> `Onboarding your TPP` directory.

Refer to <<#_on_boarding_with_an_aspsp,On-boarding with an ASPSP>> for more information.

==== Check Mutual Authentication Set Up
. Select `Dynamic Registration` -> `Onboarding your TPP` -> `test mtls before on-boarding`
. Click `Send` and expect a similar response

[source,json]
----
{
    "issuerId": "5fa14c3a0626b40014b77b62",
    "authorities": [
        "PSD2_PSP_AI",
        "PSD2_PSP_IC",
        "PSD2_PSP_PI",
        "ROLE_EIDAS",
        "ROLE_FORGEROCK_EXTERNAL_APP",
        "ROLE_TPP",
        "UNREGISTERED_TPP"
    ]
}
----

==== Get Current Software Statement
. Select `Dynamic Registration` -> `Onboarding your TPP` -> `Current software statement`
. Click `Send` and expect a similar response

[source,json]
----
{
    "id": "5fa14c3a0626b40014b77b62",
    "name": "Postman",
    "description": "app description",
    "mode": "TEST",
    "roles": [
        "CBPII",
        "AISP",
        "PISP",
        "DATA"
    ],
    "status": "ACTIVE",
    "redirectUris": [
        "https://www.google.com"
    ],
    "applicationId": "5fa14c3a0e02d30017b54804",
    "software_id": "5fa14c3a0626b40014b77b62",
    "org_id": "5fa1244bfe096000142f9248"
}
----

==== Generating an SSA
. Select `Dynamic Registration` -> `Onboarding your TPP` -> `Generate SSA`
. Click `Send` and expect JWT token in the response
[source,shell]
----
eyJraWQiOiIyMTA5ODRjOTEwZTg1ZjljMDRkNjZjZDdiNGNkMDAxOThjMWZhZjJhIiwiYWxnIjoiUFMyNTYifQ.eyJvcmdfandrc19lbmRwb2ludCI6IlRPRE8iLCJzb2Z0d2.......MdSnV9VtWAFm1Sxfzw8pgy4lytpYzRMVUpeRTz2ysV6TBYsONKNSUTZ3-81EWr5B....
----

==== Generating a Registration JWT
. Select `Dynamic Registration` -> `Onboarding your TPP` -> `Generate registration JWT`
. Click `Send` and expect JWT token in the response
[source, shell]
----
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QeyJraWQiOiIzMmQyNDA0ZW ......
----

==== Registering the TPP
. Select `Dynamic Registration` -> `Onboarding your TPP` -> `Dynamic Registration`
. Click `Send` and expect a similar response.

NOTE: There is an expiry time on the JWT so if you don't make request soon enough you may get an expired response. It means that you need start again from <<#_generating_an_ssa, Generating an SSA>>
[source,json]
----
{
    "Code": "OBRI.TPP.Registration",
    "Id": "e9864e077f304685",
    "Message": "An error happened when using the TPP registration endpoint",
    "Errors": [
        {
            "ErrorCode": "OBRI.Registration.Request.Invalid",
            "Message": "The registration request JWT is invalid. Reason 'JWT expired'",
            "Url": "https://docs.{{obriDomain}}.forgerock.financial:443/errors#OBRI.Registration.Request.Invalid"
        }
    ]
}
----

If the JWT haven't expire expect a response similar to below:

[source,json]
----
{
    "scopes": [
        "openid",
        "eventpolling",
        "payments",
        "fundsconfirmations",
        "accounts"
    ],
    "scope": "openid payments fundsconfirmations accounts",
    "client_id": "3b05a12b-b1b8-4449-ba5c-2d29683e1b84",
    "redirect_uris": [
        "https://www.google.com"
    ],
    "response_types": [
        "code id_token"
    ],
    "grant_types": [
        "authorization_code",
        "refresh_token",
        "client_credentials"
    ],
    "application_type": "web",
    "client_name": "Postman",
    "jwks_uri": "https://service.directory.{{obriDomain}}.forgerock.financial:443/api/software-statement/5fa14c3a0626b40014b77b62/application/jwk_uri",
    "subject_type": "public",
    "id_token_signed_response_alg": "PS256",
    "id_token_encrypted_response_alg": "RSA-OAEP-256",
    "id_token_encrypted_response_enc": "A128CBC-HS256",
    "userinfo_signed_response_alg": "",
    "userinfo_encrypted_response_alg": "",
    "userinfo_encrypted_response_enc": "",
    "request_object_signing_alg": "PS256",
    "request_object_encryption_alg": "RSA-OAEP-256",
    "request_object_encryption_enc": "A128CBC-HS256",
    "token_endpoint_auth_method": "private_key_jwt",
    "token_endpoint_auth_signing_alg": "PS256",
    "default_max_age": "1",
    "software_statement": "eyJraWQiOiIyMTA5O.....39ZEHzBg",
    "registration_access_token": "eyJ0eXAiO....78No-i0HgjNehwmiebUqhOg",
    "registration_client_uri": "https://as.aspsp.{{obriDomain}}.forgerock.financial/oauth2/register?client_id=3b05a12b-b1b8-4449-ba5c-2d29683e1b84"
}
----

==== Check TPP Is Registered
. Select `Dynamic Registration` -> `Onboarding your TPP` -> `test mtls before on-boarding`
. Click `Send` and expect a similar response

[source,json]
----
{
    "issuerId": "3b05a12b-b1b8-4449-ba5c-2d29683e1b84",
    "authorities": [
        "PSD2_PSP_AI",
        "PSD2_PSP_IC",
        "PSD2_PSP_PI",
        "ROLE_AISP",
        "ROLE_CBPII",
        "ROLE_DATA",
        "ROLE_EIDAS",
        "ROLE_FORGEROCK_EXTERNAL_APP",
        "ROLE_PISP",
        "ROLE_TPP"
    ]
}
----

=== Accounts
For all of the examples in this section the Postman functions live in `Accounts flow` folder.

In this section you will:

. Request access to account data as the TPP
. Authorise access to account data as a user
. Retrieve account data on behalf of the user as the TPP

Refer to <<#_accessing_psu_accounts,Accessing PSU accounts>> for more information.

==== Generate Client Credential JWT As TPP
. Select `Accounts flow` -> `Access preparation` -> `Generate client assertion JWT`
. Click `Send` and expect JWT token in the response
[source,shell]
----
eyJraWQiOiIzMmQyNDA0ZWE3MGI2ZWI1MTQyOGMzMWY3MmUyNDAzZmYwYTViZGQ4IiwiYWxnIjoiUFMyNTYifQ.eyJzdWIiOi....
----
==== Generate Access Token As TPP
. Select `Accounts flow` -> `Access preparation` -> `Client credential`
. Click `Send` and expect a similar response
[source,json]
----
{
    "access_token":"eyJ0eXAiOiJKV1QiLC........J6aXAiOiJOT05FIiwia2lk",
    "scope": "openid payments accounts",
    "id_token": "eyJ0eXAiOiJKV1........QiLCJ6aXAiOiJOT05FIiwia2lk",
    "token_type": "Bearer",
    "expires_in": 86399
}
----

==== Request Account Data As TPP
. Select `Accounts flow` -> `Access preparation` -> `create account request`
. Click `Send` and expect a similar response

[source,json]
----
{
    "Data": {
        "AccountRequestId": "A435e745b-807c-4587-9466-fee067adf9a3",
        "Status": "AwaitingAuthorisation",
        "CreationDateTime": "2018-09-13T08:22:40+00:00",
        "Permissions": [
            "ReadAccountsDetail",
            "ReadBalances",
            "ReadBeneficiariesDetail",
            "ReadDirectDebits",
            "ReadProducts",
            "ReadStandingOrdersDetail",
            "ReadTransactionsCredits",
            "ReadTransactionsDebits",
            "ReadTransactionsDetail",
            "ReadOffers",
            "ReadPAN",
            "ReadParty",
            "ReadPartyPSU",
            "ReadScheduledPaymentsDetail",
            "ReadStatementsDetail"
        ],
        "Risk": {}
    }
}
----

==== Sign Payload For Accepting Account Data Request As TPP
. Select `Accounts flow` -> `Auth & Consent` -> `Generate request parameter`
. Click `Send` and expect JWT token in the response
[source,shell]
----
eyJraWQiOiIzMmQyNDA0ZWE3MGI2ZWI1MTQyOGMzMWY3MmUyNDAzZmYwYTViZGQ4IiwiYWxnIjoiUFMyNTYifQ.eyJpc3MiO.......
----
==== Authorise TPP to Accept Account Data Request As User
For this section we can only partially use Postman

. Select `Accounts flow` -> `Auth & Consent` -> `Hybrid flow`
. Select `Code` in postman under `Save`
. Select cURL from the dropdown
. Copy the URL
. Put the URL into the browser
. Log in using your username and password you used when signing up
. Select `Allow`
. Select the accounts you want the TPP to have access to
. You will now be redirected to a URL which looks like `https://www.google.com/#code=5edfe3dd-8ccd-45e3-baed-19d98b49f3da&scope=openid%20accounts&id_token={jwt}&state=10d260bf-a7d9-444a-92d9-7b7a5f088208`. The id_token has been changed to a variable `{jwt}` to reduce verbosity.
. Copy the `code` variable from the URL fragment which looks like `9b667799-c0dd-4823-b351-7431cd2f9c3d` and save this somewhere for later use. This code is called an *authorisation code*

==== Get Access Token as TPP
. Select `Accounts flow` -> `Token exchange` -> `Exchange Code`
. Go to the `Body` tab
. Override the `code` form value with your authorisation code you copied in the previous step.
. Click send and expect a similar response

[source,json]
----
{
    "access_token": "…",
    "refresh_token": "…",
    "scope": "openid accounts",
    "id_token": "…",
    "token_type": "Bearer",
    "expires_in": 86399,
    "nonce": "10d260bf-a7d9-444a-92d9-7b7a5f088208"
}
----

==== Get Account Data as TPP
. Select `Accounts flow` -> `Data access` -> `Account API V3.0` -> `Get accounts`
. Click `Send` and expect a similar response

[source,json]
----
{
    "Data": {
        "Account": [
            {
                "AccountId": "b44b9b23-2314-4d87-b097-697592bdff8e",
                "Currency": "GBP",
                "Nickname": "Household",
                "AccountType": "Personal",
                "AccountSubType": "CurrentAccount",
                "Account": [
                    {
                        "SchemeName": "SortCodeAccountNumber",
                        "Identification": "88035216110856",
                        "Name": "benjefferies"
                    }
                ]
            },
            {
                "AccountId": "f6d2c0a8-9f08-42dd-ba2a-e3a1cb56864e",
                "Currency": "GBP",
                "Nickname": "Bills",
                "Account": [
                    {
                        "SchemeName": "SortCodeAccountNumber",
                        "Identification": "63658320150292",
                        "Name": "benjefferies",
                        "SecondaryIdentification": "18433461"
                    }
                ]
            }
        ]
    },
    "Links": {
        "Self": "/accounts"
    },
    "Meta": {
        "TotalPages": 1
    }
}
----

=== Payments
For all of the examples in this section the Postman functions live in `Payment flows` -> `Payment API V3.0` -> `Domestic Payments` -> `Domestic single payment` directory.

In this section you will:

. Request a domestic payment as the TPP
. Authorise the payment as a user
. As a TPP, submit the payment that the PSU previously consented

Refer to <<#_making_a_payment,Making a payment>> for more information.

==== Generate Client Credential JWT As TPP
. Under `Payment preparation`, 'Select `Generate client credential JWT`
. Click `Send` and expect JWT token in the response

==== Generate Access Token As TPP
. Select `Client credential`
. Click `Send` and expect a similar response

[source,json]
----
{
    "access_token": "…",
    "scope": "openid payments accounts",
    "id_token": "…",
    "token_type": "Bearer",
    "expires_in": 86399
}
----

==== Request A Payment As TPP
. Select `Create domestic payment consent`
. Click `Send` and expect a similar response

[source,json]
----
{
    "Data": {
      "ConsentId": "PDC_7f078033-272d-4196-ad8f-6b1e66531dff",
      "Status": "AwaitingAuthorisation",
      …
    },
    "Risk": {
      …
    }
}
----

==== Sign Payload For Accepting Payment Request As TPP
. Select `Auth & consent` -> `Generate request parameter`
. Click `Send` and expect JWT token in the response

==== Authorise TPP to Accept Payment Request As User
For this section we can only partially use Postman

. Select `Hybrid flow`
. Select `Code` under `Save`
. Select cURL from the dropdown
. Copy the URL
. Put the URL into the browser
. Log in using your username and password you used when signing up
. Select `Allow`
. Select the account you want the payment to come from
. You will now be redirected to a URL which looks like `https://www.google.com/#code=5edfe3dd-8ccd-45e3-baed-19d98b49f3da&scope=openid%20accounts&id_token={jwt}&state=10d260bf-a7d9-444a-92d9-7b7a5f088208`. The id_token has been changed to a variable `{jwt}` to reduce verbosity.
. Copy the `code` variable from the URL fragment which looks like `9b667799-c0dd-4823-b351-7431cd2f9c3d` and save this somewhere for later use. This code is called an *authorisation code*

==== Get Access Token as TPP
. Select `Token exchange` -> `Exchange Code`
. Go to the `Body` tab
. Override the `code` form value with your authorisation code you copied in the previous step.
. Click send and expect a similar response

[source,json]
----
{
    "access_token": "…",
    "refresh_token": "…",
    "scope": "openid payments accounts",
    "id_token": "…",
    "token_type": "Bearer",
    "expires_in": 86399,
    "nonce": "10d260bf-a7d9-444a-92d9-7b7a5f088208"
}
----

==== Submit Payment Using Access token As TPP
. Select `Data access` -> `Domestic payment`
. Click `Send` and expect a similar response

[source,json]
----
{
    "Data": {
        "DomesticPaymentId": "71103d46-8eae-4da0-805c-32164797151b",
        "ConsentId": "P8606a4da-b351-44b1-8912-70f8e8cfdba4",
        "Status": "AcceptedSettlementInProcess",
        ...
    }
}
----

==== Checking Submitted Payment Status
. Select `Get Domestic Payment`
. Click `Send` and expect a similar response where the `Status` can be `AcceptedSettlementInProcess` or `AcceptedSettlementCompleted` depending on if it's been processed yet.

[source,json]
----
{
    "Data": {
        "PaymentSubmissionId": "71103d46-8eae-4da0-805c-32164797151b",
        "PaymentId": "P8606a4da-b351-44b1-8912-70f8e8cfdba4",
        "Status": "AcceptedSettlementInProcess",
        ...
    }
}
----

=== Event Notification API

For all examples in this section the Postman functions live in `Event Notifications` directory.

'''

==== Callback URL

For all examples in this section the Postman functions live in `Event Notifications` -> `Callback URL - v3.0 to v3.1.6` directory.
In this section you will:

. Register a callback URL with an ASPSP to receive event notifications.
. Optionally read, update or delete a registered callback URL.

===== Generate Client Credentials JWT As TPP
. Select `Event Notifications` -> `Callback URL - v3.0 to v3.1.6` -> `v3.0` -> `Generate client credential JWT`
. Click `Send` and expect JWT token in the response
[source,shell]
----
eyJraWQiOiI4NzkwMWRjNTI4......
----
===== Generate Access Token As TPP
. Select `Event Notifications` -> `Callback URL - v3.0 to v3.1.6` -> `v3.0` -> `Client credential`
. Click `Send` and expect a similar response
[source,json]
----
{
    "access_token": "eyJ0eXAi.......LS0LoLA",
    "expires_in": 86399,
    "id_token": "eyJraWQi........oxesuhp-b7J0w",
    "token_type": "Bearer",
    "scope": "openid payments accounts"
}
----
===== Create a Callback URL
. Select `Event Notifications` -> `Callback URL - v3.0 to v3.1.6` -> `v3.0` -> `Create Callback URL`
. Click `Send` and expect a similar response
[source,json]
----
{
    "Data": {
        "CallbackUrlId": "b44c37fb-da8f-4716-bdcf-7fd3894f6a71",
        "Url": "https://tpp-core.{{obriDomain}}.forgerock.financial/open-banking/v3.0/event-notifications",
        "Version": "3.0"
    }
}
----
===== Get Callback URL
. Select `Event Notifications` -> `Callback URL - v3.0 to v3.1.6` -> `v3.0` -> `Get Callback URLs - should be one`
. Click `Send` and expect a similar response
[source,json]
----
{
    "Data": {
        "CallbackUrl": [
            {
                "CallbackUrlId": "b44c37fb-da8f-4716-bdcf-7fd3894f6a71",
                "Url": "https://tpp-core.{{obriDomain}}.forgerock.financial/open-banking/v3.0/event-notifications",
                "Version": "3.0"
            }
        ]
    }
}
----
===== Update Callback URL
. Select `Event Notifications` -> `Callback URL - v3.0 to v3.1.6` -> `v3.0` -> `Amend Callback URL`
. Click `Send` and expect a similar response
[source,json]
----
{
    "Data": {
        "CallbackUrlId": "b44c37fb-da8f-4716-bdcf-7fd3894f6a71",
        "Url": "http://test-tpp-updated/open-banking/v3.0/event-notifications-amended",
        "Version": "3.0"
    }
}
----
===== Delete Callback URL
. Select `Event Notifications` -> `Callback URL - v3.0 to v3.1.6` -> `v3.0` -> `Delete Callback URL`
. Click `Send` and expect http code `204` and no content in the response

'''

==== Aggregated Polling
- A TPP calls an ASPSP to poll for events.
- The ASPSP responds with an array of awaiting events encoded as signed event notifications.

For all examples in this section the Postman functions live in `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` directory.
In this section you will:

- Poll event notifications by a TPP.
- Acknowledge Only: Only acknowledge receipt.
- Poll and Acknowledge: Acknowledge successfully processed event notifications and requesting more.

'''
===== Poll Only
'''
====== Generate Client Credentials JWT As TPP
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Poll Only` -> `Generate client credential JWT`
. Click `Send` and expect JWT token in the response
[source,shell]
----
eyJraWQiOiI4NzkwMWRjNTI4......
----
====== Generate Access Token As TPP
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Poll Only` -> `Client credential`
. Click `Send` and expect a similar response
[source,json]
----
{
    "access_token": "eyJ0eXAi.......LS0LoLA",
    "expires_in": 86399,
    "id_token": "eyJraWQi........oxesuhp-b7J0w",
    "token_type": "Bearer",
    "scope": "openid payments accounts"
}
----
====== Poll Event (Empty response)
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Poll Only` -> `Poll Events v3.1.2 - empty`
. Click `Send` and expect a similar response
[source,json]
----
{
    "sets": {}
}
----
====== Import an event using the FR internal API
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Poll Only` -> `Import [1] event v3.1.2 (Data api)`
. Click `Send` and expect a similar response
[source,json]
----
[
    {
        "id": "5fa2a5f2acc902001429b5eb",
        "jti": "847a8562-ae90-4a6e-bb95-35adceb10e3f",
        "signedJwt": "eyJraWQi.....7j6OQ",
        "tppId": "3b05a12b-b1b8-4449-ba5c-2d29683e1b84",
        "created": "2020-11-04T13:00:34.060Z",
        "updated": "2020-11-04T13:00:34.060Z",
        "new": false
    }
]
----
====== Poll Events - One Event
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Poll Only` -> `Poll Events v3.1.6 - One event`
. Click `Send` and expect a similar response
[source,json]
----
{
    "moreAvailable": false,
    "sets": {
        "847a8562-ae90-4a6e-bb95-35adceb10e3f": "eyJraWQ.....R7j6OQ"
    }
}
----
====== Remove Event created using FR internal data API
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Poll Only` -> `Remove events by tppId (Data api)`
. Click `Send` and expect http code **204** and no content in the response

'''
===== Acknowledge Only
'''
====== Generate Client Credentials JWT As TPP
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Acknowledge Only` -> `Generate client credential JWT`
. Click `Send` and expect JWT token in the response
[source,shell]
----
eyJraWQiOiI4NzkwMWRjNTI4......
----
====== Generate Access Token As TPP
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Acknowledge Only` -> `Client credential`
. Click `Send` and expect a similar response
[source,json]
----
{
    "access_token": "eyJ0eXAi.......LS0LoLA",
    "expires_in": 86399,
    "id_token": "eyJraWQi........oxesuhp-b7J0w",
    "token_type": "Bearer",
    "scope": "openid payments accounts"
}
----
====== Poll Event (Empty response)
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Acknowledge Only` -> `Poll Events v3.1.2 - empty`
. Click `Send` and expect a similar response
[source,json]
----
{
    "sets": {}
}
----
====== Import an event using the FR internal API
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Acknowledge Only` -> `Import [1] event v3.1.2 (Data api)`
. Click `Send` and expect a similar response
[source,json]
----
[
    {
        "id": "5fa2a5f2acc902001429b5eb",
        "jti": "847a8562-ae90-4a6e-bb95-35adceb10e3f",
        "signedJwt": "eyJraWQi.....7j6OQ",
        "tppId": "3b05a12b-b1b8-4449-ba5c-2d29683e1b84",
        "created": "2020-11-04T13:00:34.060Z",
        "updated": "2020-11-04T13:00:34.060Z",
        "new": false
    }
]
----
====== Poll Events v3.1.6 - One event
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Acknowledge Only` -> `Poll Events v3.1.6 - One event`
. Click `Send` and expect a similar response
[source,json]
----
{
    "moreAvailable": false,
    "sets": {
        "847a8562-ae90-4a6e-bb95-35adceb10e3f": "eyJraWQ.....R7j6OQ"
    }
}
----
====== Acknowledge Only Events
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Acknowledge Only` -> `Acknowledge Only Events v3.1.6 - empty`
. Clieck `Send` and expect a similar response
[source,json]
----
{
    "sets": {}
}
----
====== Remove Event created using FR internal data API
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Acknowledge Only` -> `Remove events by tppId (Data api)`
. Click `Send` and expect http code **204** and no content in the response

'''
===== Poll and Acknowledge
'''
====== Generate Client Credentials JWT As TPP
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Poll and Acknowledge` -> `Generate client credential JWT`
. Click `Send` and expect JWT token in the response
[source,shell]
----
eyJraWQiOiI4NzkwMWRjNTI4......
----
====== Generate Access Token As TPP
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Poll and Acknowledge` -> `Client credential`
. Click `Send` and expect a similar response
[source,json]
----
{
    "access_token": "eyJ0eXAi.......LS0LoLA",
    "expires_in": 86399,
    "id_token": "eyJraWQi........oxesuhp-b7J0w",
    "token_type": "Bearer",
    "scope": "openid payments accounts"
}
----
====== Poll Event (Empty response)
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Poll and Acknowledge` -> `Poll Events v3.1.2 - empty`
. Click `Send` and expect a similar response
[source,json]
----
{
    "sets": {}
}
----
====== Import two events using the FR internal API
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Poll and Acknowledge` -> `Import [2] event v3.1.2 (Data api)`
. Click `Send` and expect a similar response
[source,json]
----
[
    {
        "id": "5fa2b6d8acc902001429b5ed",
        "jti": "6ee27018-ac7e-4d0d-8ee6-bc22af8ae477",
        "signedJwt": "eyJraWQ....QESERA",
        "tppId": "3b05a12b-b1b8-4449-ba5c-2d29683e1b84",
        "created": "2020-11-04T14:12:40.589Z",
        "updated": "2020-11-04T14:12:40.589Z",
        "new": false
    },
    {
        "id": "5fa2b6d8acc902001429b5ee",
        "jti": "864b2eb6-5c32-43be-a0d4-c36cdea350f4",
        "signedJwt": "eyJraWQiOi....1wbwQ",
        "tppId": "3b05a12b-b1b8-4449-ba5c-2d29683e1b84",
        "created": "2020-11-04T14:12:40.650Z",
        "updated": "2020-11-04T14:12:40.650Z",
        "new": false
    }
]
----
====== Poll Events v3.1.6 - Two events
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Poll and Acknowledge` -> `Poll Events v3.1.6 - Two event`
. Click `Send` and expect a similar response
[source,json]
----
{
    "moreAvailable": false,
    "sets": {
        "864b2eb6-5c32-43be-a0d4-c36cdea350f4": "eyJraWQ....RX1wbwQ",
        "6ee27018-ac7e-4d0d-8ee6-bc22af8ae477": "eyJraWQ....QESERA"
    }
}
----
====== Poll and Acknowledge
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Poll and Acknowledge` -> `Acknowledge Only Events v3.1.6 - empty`
. Clieck `Send` and expect a similar response
[source,json]
----
{
    "moreAvailable": false,
    "sets": {
        "6ee27018-ac7e-4d0d-8ee6-bc22af8ae477": "eyJraWQ....QESERA"
    }
}
----
====== Remove Event created using FR internal data API
. Select `Event Notifications` -> `Aggregated Polling - v3.1.2 to v3.1.6` -> `Poll and Acknowledge` -> `Remove events by tppId (Data api)`
. Click `Send` and expect http code **204** and no content in the response

'''
==== Event Notification Subscription
For all examples in this section the Postman functions live in `Event Notifications` → `Event Notification Subscription - v3.1.2 to v3.1.6` directory.
In this section you will:

- Create an event subscription resource.
- Access an event subscription resource.
- Update an event subscription resource.
- Delete an event subscription resource.

'''
===== Generate Client Credentials JWT As TPP
. Select `Event Notifications` -> `Event Notification Subscription - v3.1.2 to v3.1.6` -> `Generate client credential JWT`
. Click `Send` and expect JWT token in the response
[source,shell]
----
eyJraWQiOiI4NzkwMWRjNTI4......
----
===== Generate Access Token As TPP
. Select `Event Notifications` -> `Event Notification Subscription - v3.1.2 to v3.1.6` -> `Client credential`
. Click `Send` and expect a similar response
[source,json]
----
{
    "access_token": "eyJ0eXAi.......LS0LoLA",
    "expires_in": 86399,
    "id_token": "eyJraWQi........oxesuhp-b7J0w",
    "token_type": "Bearer",
    "scope": "openid payments accounts"
}
----
===== Create an Event subscription
. Select `Event Notifications` -> `Event Notification Subscription - v3.1.2 to v3.1.6` -> `Create event subscription v3.1.2`
. Click `Send` and expect a similar response
[source,json]
----
{
    "Data": {
        "EventSubscriptionId": "5336cc75-4bfb-4ff1-927d-6c60e8e93630",
        "CallbackUrl": "https://tpp.com/open-banking/v3.1.2/event-notifications",
        "Version": "3.1.2"
    },
    "Links": {
        "Self": "https://matls.rs.aspsp.smiths-rc2.forgerock.financial/open-banking/v3.1.2/callback-urls"
    },
    "Meta": {}
}
----
===== Create an Event subscription - conflict test
. Select `Event Notifications` -> `Event Notification Subscription - v3.1.2 to v3.1.6` -> `Create event subscription v3.1.3 - Conflict 409`
. Click `Send` and expect a similar response
[source,json]
----
{
    "Code": "OBRI.Request.Invalid",
    "Id": "b4dae9a137850849",
    "Message": "An error happened when parsing the request arguments",
    "Errors": [
        {
            "ErrorCode": "OBRI.EventSubscription.Exists",
            "Message": "An event subscription already exists for this TPP. Please use PUT and DELETE methods to amend or remove.",
            "Url": "https://docs.smiths-rc2.forgerock.financial:443/errors#OBRI.EventSubscription.Exists"
        }
    ]
}
----
===== Get event subscription
. Select `Event Notifications` -> `Event Notification Subscription - v3.1.2 to v3.1.6` -> `Get event subscription 3.1.2 via api v3.1.4`
. Click `Send` and expect a similar response
[source,json]
----
{
    "Data": {
        "EventSubscription": [
            {
                "EventSubscriptionId": "5336cc75-4bfb-4ff1-927d-6c60e8e93630",
                "CallbackUrl": "https://tpp.com/open-banking/v3.1.2/event-notifications",
                "Version": "3.1.2"
            }
        ]
    },
    "Links": {
        "Self": "https://matls.rs.aspsp.smiths-rc2.forgerock.financial/open-banking/v3.1.4/callback-urls"
    },
    "Meta": {}
}
----
===== Update event subscription
. Select `Event Notifications` -> `Event Notification Subscription - v3.1.2 to v3.1.6` -> `Update event subscription 3.1.2 to 3.1.3 via api v3.1.5`
. Click `Send` and expect a similar response
[source,json]
----
{
    "Data": {
        "EventSubscriptionId": "5336cc75-4bfb-4ff1-927d-6c60e8e93630",
        "CallbackUrl": "https://tpp.com/open-banking/v3.1.3/event-notifications",
        "Version": "3.1.3"
    },
    "Links": {
        "Self": "https://matls.rs.aspsp.smiths-rc2.forgerock.financial/open-banking/v3.1.5/callback-urls"
    },
    "Meta": {}
}
----
===== Delete event subscription
. Select `Event Notifications` -> `Event Notification Subscription - v3.1.2 to v3.1.6` -> `Delete event subscription v3.1.6`
. Click `Send` and expect http code **204** and no content response
